In [ ]:
import pandas as pd
import numpy as np

In [ ]:
asa=[]
for i in range(97):
    asa.append(i)

In [ ]:
df=pd.read_csv("ECG200_TRAIN.csv",delimiter="  ")
df = df.set_axis(asa, axis=1, inplace=False)

/usr/local/lib/python3.7/dist-packages/pandas/util/_decorators.py:311: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  return func(*args, **kwargs)

In [ ]:
df

,0,1,2,3,4,5,6,7,8,9,...,87,88,89,90,91,92,93,94,95,96
0,1.0,0.147647,0.804668,0.367771,0.243894,0.026614,-0.274402,0.096731,-0.747731,-1.609777,...,-0.533503,-0.400228,0.176084,1.111768,2.438428,2.734889,1.736054,0.036857,-1.265074,-0.208024
1,-1.0,0.316646,0.243199,0.370471,1.063738,1.678187,1.759558,1.697717,1.612159,1.168188,...,0.764229,0.610621,0.552900,0.566786,0.604002,0.777068,0.812345,0.748848,0.818042,0.539347
2,-1.0,1.168874,2.075901,1.760141,1.606446,1.949046,1.302842,0.459332,0.516412,0.852180,...,0.419006,0.723888,1.323947,2.136488,1.746597,1.470220,1.893512,1.256949,0.800407,0.731540
3,1.0,0.648658,0.752026,2.636231,3.455716,2.118157,0.520620,-0.188627,0.780818,0.933775,...,-0.097869,-0.136787,-0.340237,-0.089441,-0.080297,-0.192584,-0.304704,-0.454556,0.314590,0.582190
4,1.0,0.404733,1.280859,2.515148,1.299519,1.453432,0.474275,-1.396562,-0.647081,0.431945,...,0.376469,0.277811,0.225676,0.159091,0.408354,0.540015,-0.027791,0.203476,0.346964,0.339185
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,1.0,0.581277,0.876188,1.042767,1.796120,2.541399,2.246653,1.500387,1.031521,0.382672,...,1.002770,0.907869,0.916457,0.923975,0.767357,0.656223,0.762357,0.501373,-0.333336,-0.524546
95,-1.0,2.689017,2.708703,2.008381,2.235800,1.516982,0.029916,-0.561346,-0.793702,-0.979371,...,-0.136610,-0.072176,-0.082738,-0.138468,-0.120396,-0.089411,-0.243141,-0.119710,0.124042,0.273463
96,-1.0,0.197677,0.455417,0.973110,1.935956,2.259463,1.741341,1.158296,0.418241,-0.071605,...,0.482452,0.325569,0.247991,0.184127,0.050358,0.241988,0.331451,-0.120006,0.042423,0.343293
97,1.0,0.179500,1.038409,1.946421,2.705141,1.670706,-0.101167,-1.578876,-0.750906,0.175310,...,0.324323,0.330489,0.111953,0.448948,0.567132,0.136757,0.444768,0.151050,0.193378,0.451709
98,1.0,0.073124,0.776054,2.181336,3.440325,2.168475,0.497315,-0.924284,-1.499227,-0.679328,...,-0.058935,-0.130638,-0.347235,-0.177933,-0.060332,-0.347634,-0.447443,-0.066689,-0.178448,-0.256052

In [ ]:
df[0].value_counts()

 1.0    69
-1.0    30
Name: 0, dtype: int64

In [ ]:
aa=df.values
aa

array([[ 1.        ,  0.1476469 ,  0.8046684 , ...,  0.03685655,
        -1.2650744 , -0.20802439],
       [-1.        ,  0.31664616,  0.24319908, ...,  0.74884814,
         0.81804204,  0.53934704],
       [-1.        ,  1.1688741 ,  2.0759008 , ...,  1.2569493 ,
         0.80040658,  0.73153981],
       ...,
       [-1.        ,  0.19767692,  0.45541658, ..., -0.1200061 ,
         0.04242264,  0.34329344],
       [ 1.        ,  0.17950028,  1.0384092 , ...,  0.15104997,
         0.19337751,  0.45170853],
       [ 1.        ,  0.07312418,  0.77605406, ..., -0.06668896,
        -0.17844792, -0.25605159]])

In [ ]:
t1=[]
t2=[]
count=0
for idx,i in enumerate(aa):
    if(i[0]==1.0):
        t1.append(i)
    else:
        t2.append(i)

In [ ]:
k = 6
kfold = []
for i in range(k):
    kfold.append([])
for idx, i in enumerate(t1):
    kfold[idx % k].append(i)
for idx, i in enumerate(t2):
    kfold[idx % k].append(i)
for i in kfold:
    print(len(i))

17
17
17
16
16
16

In [ ]:
li=[]
for j in range(n):

    df1=pd.DataFrame()
    df2=pd.DataFrame()
    for i in range(n):
        if(i!=j):
            df1=df1.append(endlist[i])
        else:
            df2=df1.append(endlist[j])
    import xgboost as xgb            
    X_train, y_train,X_test, y_test=df1.drop(0,axis=1,),df1[0],df2.drop(0,axis=1,),df2[0]
    from sklearn.linear_model import LinearRegression
    from sklearn.metrics import confusion_matrix
    my_model = xgb.XGBClassifier()
    my_model.fit(X_train, y_train)
    # print(my_model.score(X_test, y_test),end="\n\n")
    y_pred = my_model.predict(X_test)
    from sklearn.metrics import f1_score
    li.append(f1_score(y_test, y_pred))

print("This is the mean of k accuracies: ",np.mean(li),end="\n\n")
print("These are k accuracies: ",li,end="\n\n")

This is the mean of k accuracies:  0.9398882146145825

These are k accuracies:  [0.8181818181818182, 0.9361702127659574, 0.9863013698630138, 0.9375000000000001, 0.9827586206896551, 0.9784172661870504]

In [ ]:
from numpy import mean
from numpy import std
from sklearn.datasets import make_classification
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
import xgboost as xgb            
X, y=df.drop(0,axis=1,),df[0]
cv = KFold(n_splits=4, random_state=0, shuffle=True)
model = xgb.XGBClassifier()
scores = cross_val_score(model, X, y, scoring='f1', cv=cv, n_jobs=-1)
# report performance
print('Accuracy: %.3f (%.3f)' % (mean(scores), std(scores)))

Accuracy: 0.847 (0.027)

#Comparison between sklearn Kfold and our Kfold

So the f1 score returned by our kfold is better than the pre built it is because we have the control over what is going on inside ours where as in the pre built we just send everything to the model and the model decides what to do