In [1]:
import numpy as np
import random

In [3]:
#Task 1

v1=np.random.randint(2,10,size=(1,2))
v1[0]

array([7, 9])

In [9]:
#Task 2
t=[]
t.append(1)
t.append((-1 * (v1[0][0]*1))/v1[0][1])
print(t)
np.dot(v1[0],t)

[1, -0.7777777777777778]

0.0

In [10]:
np.linalg.norm(v1)

11.40175425099138

In [11]:
#Task 3
temp=v1/np.linalg.norm(v1)
temp1=np.dot(v1,t)/np.linalg.norm(v1)
temp2=temp1*temp
temp2

array([[0., 0.]])

In [13]:
#Task 3

temp=v1/np.linalg.norm(t)
temp1=np.dot(t,v1[0])/np.linalg.norm(t)
temp2=temp1*temp
temp2

array([[0., 0.]])

# Task 4
### We can not find the intitial vector from projection as projection is zero

In [15]:
#Task 5
v1=np.random.randint(2,10,size=(1,2))
v2=np.random.randint(2,10,size=(1,2))
#projection of v1 on v2
temp=v1/np.linalg.norm(v1)
temp1=np.dot(v1[0],v2[0])/np.linalg.norm(v1)
temp2=temp1*temp
print(temp2)
#projection of v2 on v1
temp=v2/np.linalg.norm(v2)
temp1=np.dot(v2[0],v1[0])/np.linalg.norm(v2)
temp2=temp1*temp
print(temp2)

[[2.89655172 7.24137931]]
[[3.5 3.5]]

In [29]:
from sklearn import datasets
from sklearn.decomposition import PCA

# import some data to play with
iris = datasets.load_iris()
X = iris.data  # we only take the first two features.
y = iris.target
from numpy.linalg import eig
aa=np.dot(X,X.T)
x,y=eig(aa)
print(x[0])
print(y[0])

(9208.305070314853+0j)
[ 6.16168450e-02+0.j         -1.29611444e-01+0.j
 -2.13859674e-03+0.j         -1.63819140e-03+0.j
  7.21340090e-02-0.05708074j  7.21340090e-02+0.05708074j
 -6.94947106e-02-0.01016376j -6.94947106e-02+0.01016376j
 -1.95898529e-02-0.01885361j -1.95898529e-02+0.01885361j
 -3.68698380e-02+0.j         -5.69883035e-02+0.j
  1.90796199e-02+0.01865112j  1.90796199e-02-0.01865112j
  4.66233900e-02-0.05581612j  4.66233900e-02+0.05581612j
 -1.81596605e-02-0.0116075j  -1.81596605e-02+0.0116075j
  6.61269340e-02+0.00559094j  6.61269340e-02-0.00559094j
 -1.15716359e-02+0.01430789j -1.15716359e-02-0.01430789j
  4.33822047e-02+0.00292608j  4.33822047e-02-0.00292608j
 -5.05981292e-02-0.00818666j -5.05981292e-02+0.00818666j
 -5.63824827e-02-0.03045246j -5.63824827e-02+0.03045246j
  3.25584160e-02-0.1134158j   3.25584160e-02+0.1134158j
 -2.47849535e-03+0.00395049j -2.47849535e-03-0.00395049j
 -3.67507286e-02+0.01859895j -3.67507286e-02-0.01859895j
  1.77223307e-02+0.00581941j  1.77223307e-02-0.00581941j
 -1.75924478e-02+0.j          8.09011926e-04-0.02725219j
  8.09011926e-04+0.02725219j  2.15082835e-04+0.01753332j
  2.15082835e-04-0.01753332j  4.81258364e-02+0.0025845j
  4.81258364e-02-0.0025845j  -6.55725261e-03+0.0494463j
 -6.55725261e-03-0.0494463j   7.64565382e-02+0.02851235j
  7.64565382e-02-0.02851235j  5.49079270e-02-0.00107855j
  5.49079270e-02+0.00107855j  3.73903229e-02+0.0143305j
  3.73903229e-02-0.0143305j  -2.94687315e-03+0.0179954j
 -2.94687315e-03-0.0179954j  -3.94353215e-02+0.j
  5.92437242e-03+0.j          3.34809797e-02+0.05155035j
  3.34809797e-02-0.05155035j -5.90286285e-02+0.05559006j
 -5.90286285e-02-0.05559006j -2.23417573e-02+0.j
 -4.25456911e-02-0.03586168j -4.25456911e-02+0.03586168j
  4.76269305e-02-0.04459898j  4.76269305e-02+0.04459898j
  6.30820734e-02-0.02681194j  6.30820734e-02+0.02681194j
 -1.19486221e-02-0.01516262j -1.19486221e-02+0.01516262j
  3.41572377e-02-0.07818261j  3.41572377e-02+0.07818261j
  5.24533646e-02+0.03086121j  5.24533646e-02-0.03086121j
 -3.25964039e-02-0.04135859j -3.25964039e-02+0.04135859j
 -6.99054805e-03+0.07211689j -6.99054805e-03-0.07211689j
 -1.55671343e-02-0.0119213j  -1.55671343e-02+0.0119213j
 -4.03467595e-02+0.06033823j -4.03467595e-02-0.06033823j
  2.14947583e-02+0.01131204j  2.14947583e-02-0.01131204j
  1.98268528e-02+0.04245199j  1.98268528e-02-0.04245199j
 -2.71255306e-03+0.00621647j -2.71255306e-03-0.00621647j
  2.54390837e-02+0.j          4.35586077e-02-0.00575447j
  4.35586077e-02+0.00575447j -5.57243572e-02+0.01954269j
 -5.57243572e-02-0.01954269j  4.06549818e-02-0.04484157j
  4.06549818e-02+0.04484157j  6.16680014e-03-0.00118261j
  6.16680014e-03+0.00118261j -1.08760521e-02+0.j
  4.52460094e-02-0.06667429j  4.52460094e-02+0.06667429j
 -1.11379379e-01+0.00597741j -1.11379379e-01-0.00597741j
  8.60660678e-02+0.00101958j  8.60660678e-02-0.00101958j
 -2.96823941e-03-0.06206853j -2.96823941e-03+0.06206853j
  6.55590262e-02+0.03362008j  6.55590262e-02-0.03362008j
 -5.16104022e-03+0.03977118j -5.16104022e-03-0.03977118j
 -2.00661684e-02-0.07039549j -2.00661684e-02+0.07039549j
 -6.94558226e-02+0.01296936j -6.94558226e-02-0.01296936j
  3.79855718e-02-0.01692979j  3.79855718e-02+0.01692979j
  4.64841750e-02-0.04641969j  4.64841750e-02+0.04641969j
  1.96020206e-02+0.00224062j  1.96020206e-02-0.00224062j
  3.67646838e-02-0.02449052j  3.67646838e-02+0.02449052j
 -4.49561281e-04+0.j         -2.13573092e-02-0.00496708j
 -2.13573092e-02+0.00496708j -7.99197186e-02-0.03963005j
 -7.99197186e-02+0.03963005j -7.01007169e-02+0.04901276j
 -7.01007169e-02-0.04901276j  1.76415187e-02+0.j
 -1.04395871e-02+0.05446145j -1.04395871e-02-0.05446145j
  4.65614547e-02-0.04003026j  4.65614547e-02+0.04003026j
  4.19276522e-02+0.00507902j  4.19276522e-02-0.00507902j
 -5.04290523e-02+0.03325926j -5.04290523e-02-0.03325926j
  2.78792350e-02-0.01377092j  2.78792350e-02+0.01377092j
 -1.77112834e-02-0.00488545j -1.77112834e-02+0.00488545j
 -1.04068877e-01+0.j          1.41899410e-02-0.00331105j
  1.41899410e-02+0.00331105j  4.15583279e-02+0.j
 -2.30255761e-02+0.j          3.37009804e-02+0.j
 -6.80315106e-02+0.j          8.63351870e-02+0.j
  7.89834941e-02+0.j         -9.30055914e-16+0.j        ]

In [33]:
df = np.mean(X , axis=0)
temps=X-df
import pandas as pd
df1=pd.DataFrame(temps)
df1.columns=[	"sepal length (cm)"	,"sepal width (cm)"	,"petal length (cm)",	"petal width (cm)"]
df1

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0            -0.743333          0.442667             -2.358         -0.999333
1            -0.943333         -0.057333             -2.358         -0.999333
2            -1.143333          0.142667             -2.458         -0.999333
3            -1.243333          0.042667             -2.258         -0.999333
4            -0.843333          0.542667             -2.358         -0.999333
..                 ...               ...                ...               ...
145           0.856667         -0.057333              1.442          1.100667
146           0.456667         -0.557333              1.242          0.700667
147           0.656667         -0.057333              1.442          0.800667
148           0.356667          0.342667              1.642          1.100667
149           0.056667         -0.057333              1.342          0.600667

[150 rows x 4 columns]

In [44]:
df2=pd.read_csv("/content/ECG200_TRAIN (1).csv",delimiter="  ")
me=np.mean(df2.values,axis=0)
temps=df2.values-me
temps

/usr/local/lib/python3.7/dist-packages/pandas/util/_decorators.py:311: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  return func(*args, **kwargs)

array([[ 0.60606061, -0.56287534, -0.62637147, ..., -0.24174343,
        -1.44254023, -0.3802724 ],
       [-1.39393939, -0.39387608, -1.18784079, ...,  0.47024815,
         0.64057621,  0.36709903],
       [-1.39393939,  0.45835186,  0.64486093, ...,  0.97834931,
         0.62294075,  0.5592918 ],
       ...,
       [-1.39393939, -0.51284532, -0.97562329, ..., -0.39860609,
        -0.1350432 ,  0.17104543],
       [ 0.60606061, -0.53102196, -0.39263067, ..., -0.12755002,
         0.01591168,  0.27946052],
       [ 0.60606061, -0.63739806, -0.65498581, ..., -0.34528895,
        -0.35591375, -0.4282996 ]])

In [45]:
import pandas as pd
df3=pd.DataFrame(temps)

In [46]:
df3

,0,1,2,3,4,5,6,7,8,9,...,87,88,89,90,91,92,93,94,95,96
0,0.606061,-0.562875,-0.626371,-1.684678,-1.889607,-1.519094,-1.021311,-0.169213,-1.069893,-1.976327,...,-0.716434,-0.570110,-0.024641,0.829306,2.027689,2.277342,1.349421,-0.241743,-1.442540,-0.380272
1,-1.393939,-0.393876,-1.187841,-1.681978,-1.069763,0.132479,1.012649,1.431773,1.289997,0.801638,...,0.581298,0.440740,0.352175,0.284324,0.193263,0.319521,0.425713,0.470248,0.640576,0.367099
2,-1.393939,0.458352,0.644861,-0.292309,-0.527055,0.403337,0.555934,0.193388,0.194250,0.485630,...,0.236076,0.554006,1.123222,1.854026,1.335857,1.012674,1.506879,0.978349,0.622941,0.559292
3,0.606061,-0.061865,-0.679014,0.583781,1.322214,0.572449,-0.226288,-0.454570,0.458656,0.567225,...,-0.280800,-0.306668,-0.540962,-0.371903,-0.491036,-0.650131,-0.691337,-0.733156,0.137124,0.409941
4,0.606061,-0.305790,-0.150181,0.462698,-0.833982,-0.092276,-0.272633,-1.662506,-0.969243,0.065395,...,0.193538,0.107930,0.024951,-0.123371,-0.002385,0.082468,-0.414424,-0.075124,0.169498,0.166937
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,0.606061,-0.129245,-0.554852,-1.009683,-0.337381,0.995691,1.499744,1.234443,0.709358,0.016122,...,0.819840,0.737987,0.715732,0.641513,0.356618,0.198677,0.375724,0.222773,-0.510802,-0.696794
95,-1.393939,1.978495,1.277664,-0.044068,0.102299,-0.028727,-0.716992,-0.827290,-1.115864,-1.345921,...,-0.319541,-0.242057,-0.283463,-0.420930,-0.531135,-0.546958,-0.629773,-0.398310,-0.053423,0.101215
96,-1.393939,-0.512845,-0.975623,-1.079340,-0.197545,0.713755,0.994432,0.892352,0.096079,-0.438155,...,0.299522,0.155688,0.047266,-0.098335,-0.360381,-0.215558,-0.055182,-0.398606,-0.135043,0.171045
97,0.606061,-0.531022,-0.392631,-0.106029,0.571640,0.124998,-0.848075,-1.844820,-1.073068,-0.191240,...,0.141393,0.160607,-0.088772,0.166486,0.156393,-0.320789,0.058135,-0.127550,0.015912,0.279461
98,0.606061,-0.637398,-0.654986,0.128886,1.306824,0.622767,-0.249593,-1.190228,-1.821389,-1.045878,...,-0.241866,-0.300519,-0.547960,-0.460395,-0.471071,-0.805180,-0.834076,-0.345289,-0.355914,-0.428300